[build]
  publish = "packages/frontend/build/"

[context.branch-deploy.environment]
  NODE_ENV = "development"
[context.deploy-preview]
  NODE_ENV = "development"

# uncomment for frontend SPA routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
